stellar-web/src/main/java/stellar/web/faces/LocaleBean.java
package stellar.web.faces;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;

@ManagedBean
@SessionScoped
public class LocaleBean {

    private String selectedLocale =
            FacesContext.
                    getCurrentInstance().
                    getViewRoot().
                    getLocale()
            .getLanguage();


    public String getSelectedLocale() {
        return selectedLocale;
    }

    public void setSelectedLocale(String selectedLocale) {
        FacesContext.
                getCurrentInstance().
                getViewRoot().
                setLocale( new Locale(selectedLocale) );
        this.selectedLocale = selectedLocale;
    }


    public List<Locale> getSupportedLocales(){
        Iterator<Locale> itr =
                FacesContext.
                        getCurrentInstance().
                        getApplication().
                        getSupportedLocales();
        List<Locale> locales = new ArrayList<>();
        itr.forEachRemaining(l->locales.add(l));

        locales.add(FacesContext.
                getCurrentInstance().
                getApplication().
                getDefaultLocale()
        );

        return locales;
    }


}

stellar-web/src/main/java/stellar/web/faces/SearchBean.java
package stellar.web.faces;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.context.FacesContext;
import java.io.Serializable;
import java.util.logging.Logger;

@ManagedBean
public class SearchBean implements Serializable {

    Logger logger = Logger.getLogger(SearchBean.class.getName());

    private String phrase;

    private int systemId;

    public SearchBean(){
        logger.severe("search bean constructed!");
    }

    @PostConstruct
    public void initSystemId(){
        String systemIdString =
                FacesContext.
                        getCurrentInstance().
                        getExternalContext().
                        getRequestParameterMap().
                        get("systemId");
        if(systemIdString!=null && !systemIdString.trim().isEmpty()){
            this.systemId = Integer.parseInt(systemIdString);
        }
    }

    public boolean isPhrasePresent(){
        return phrase!=null && !phrase.trim().isEmpty();
    }

    public String getPhrase() {
        return phrase;
    }

    public void setPhrase(String phrase) {
        this.phrase = phrase;
    }

    public int getSystemId() {
        return systemId;
    }

    public void setSystemId(int systemId) {
        this.systemId = systemId;
    }


}

stellar-web/src/main/java/stellar/web/faces/StellarBean.java
package stellar.web.faces;

import stellar.entities.Planet;
import stellar.entities.PlanetarySystem;
import stellar.service.api.StellarService;
import stellar.service.impl.StellarServiceImpl;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;
import java.util.List;
import java.util.logging.Logger;

@ManagedBean(name="stellarBean")
public class StellarBean {

    //@ManagedProperty("#{stellarService}")

    @Inject
    private Logger logger/* = Logger.getLogger(StellarBean.class.getName())*/;

    @Inject
    private StellarService service;

    @ManagedProperty("#{searchBean}")
    private SearchBean searchBean;


    public List<PlanetarySystem> getPlanetarySystems() {
        logger.info("about to search planetary systems");
        if (searchBean.isPhrasePresent()) {
            return service.getSystemsByName(searchBean.getPhrase());
        } else {
            return service.getSystems();
        }
    }

    public PlanetarySystem getPlanetarySystem(int systemId) {
        return service.getSystemById(systemId);
    }

    public List<Planet> getPlanets() {

        if (searchBean.isPhrasePresent()) {
            return service.getPlanets(service.getSystemById(searchBean.getSystemId()), searchBean.getPhrase());
        } else {
            return service.getPlanets(service.getSystemById(searchBean.getSystemId()));
        }
    }


    public SearchBean getSearchBean() {
        return searchBean;
    }

    public void setSearchBean(SearchBean searchBean) {
        this.searchBean = searchBean;
    }
}

stellar-web/src/main/java/stellar/web/servlet/PlanetsServlet.java
package stellar.web.servlet;

import stellar.entities.Page;
import stellar.entities.Planet;
import stellar.service.api.StellarService;
import stellar.service.impl.StellarServiceImpl;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.logging.Logger;

public class PlanetsServlet extends HttpServlet {

    private Logger logger = Logger.getLogger(PlanetsServlet.class.getName());

    @Inject
    private StellarService service;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        int systemId = Integer.parseInt(req.getParameter("systemId"));

        if(systemId==3){
            throw new IllegalArgumentException("illegal system id");
        }
        logger.info("about to fetch planets of system " + systemId);

        int pageSize = 3;

        int pageNo = 1;
        if(req.getParameterMap().containsKey("pageNo")){
            pageNo = Integer.parseInt(req.getParameter("pageNo"));
        }

        Page<Planet> planetPage = service.getPlanetsPage(
                service.getSystemById(systemId),
                pageNo,
                pageSize
        );

        req.setAttribute("planets", planetPage);

        req.getRequestDispatcher("/WEB-INF/jsp/planets.jsp").forward(req, resp);
    }
}

stellar-web/src/main/java/stellar/web/servlet/SystemsServlet.java
package stellar.web.servlet;

import stellar.entities.PlanetarySystem;
import stellar.service.api.StellarService;
import stellar.service.impl.StellarServiceImpl;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Logger;

public class SystemsServlet extends HttpServlet {

    private Logger logger = Logger.getLogger(SystemsServlet.class.getName());

    @Inject
    private StellarService service;

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {

        logger.info("about to fetch planetary systems");

        List<PlanetarySystem> systems;
        if(req.getParameterMap().containsKey("systemId")) {
            int systemId = Integer.parseInt(req.getParameter("systemId"));
            systems = Arrays.asList(service.getSystemById(systemId));
        } else {
            systems = service.getSystems();
        }

        String languages = req.getHeader("Accept-Language");

        req.setAttribute("systems", systems);

        req.getRequestDispatcher("/WEB-INF/jsp/systems.jsp").forward(req, resp);

        /*StringBuilder sb = new StringBuilder();

        sb.append("<html><body>"+
                "<table><tr><th>Name</th><th>Star</th></tr>");

        systems.forEach(
                s-> sb.append("<tr><td>").append(s.getName()).append("</td><td>").append(s.getStar()).append("</td></tr>")
        );

        sb.append("</table></body></html>");

        resp.getWriter().write(sb.toString());*/

    }
}

stellar-web/src/main/webapp/WEB-INF/jsp/footer.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>


    </section>
</article>
<footer>
    <span>JSP</span>
</footer>

</body>
</html>

stellar-web/src/main/webapp/WEB-INF/jsp/header.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<html>
<head>
    <title>Planetary Systems</title>
    <link rel="stylesheet" href="<c:url value="/resources/css/style.css"/>"/>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">
</head>
<body>

<header>
    <nav>
        <ul>
            <li class="active"><a
                    href="./systems">Stellar Catalogue</a></li>
        </ul>
        <span></span>
    </nav>
</header>

<article>
    <jsp:include page="search.jsp"/>
    <section class="data">

stellar-web/src/main/webapp/WEB-INF/jsp/planets.jsp
<%@ page import="stellar.entities.Planet" %>
<%@ page import="stellar.entities.Page" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>

    <jsp:include page="header.jsp"/>

    <table>
        <tr>
            <th>Id</th>
            <th>Name</th>
        </tr>

        <c:forEach items="${planets.items}" var="p">
        <tr>
            <td>${p.id}</td>
            <td>${p.name}</td>
        </tr>
        </c:forEach>

        <tr>
            <td colspan="2">
                <c:forEach var="i" begin="1" end="${planets.pageCount}">
                    <c:choose>
                        <c:when test="${planets.pageNo eq i}">
                            ${i}
                        </c:when>
                        <c:otherwise>
                            <a href="./planets?systemId=${param.systemId}&pageNo=${i}">
                                    ${i}
                            </a>
                        </c:otherwise>
                    </c:choose>
                </c:forEach>
            </td>
        </tr>

    </table>


    <jsp:include page="footer.jsp"/>

stellar-web/src/main/webapp/WEB-INF/jsp/search.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div id="search">
    <span>SEARCH</span>
    <form method="post" action="./systems" class="search-container" enctype="application/x-www-form-urlencoded">
        <input type="text"><input type="submit" value="">
    </form>
</div>

stellar-web/src/main/webapp/WEB-INF/jsp/systems.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>


<jsp:include page="header.jsp"/>

<span>Planetary Systems</span>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Star</th>
            <th>Distance</th>
        </tr>
    </thead>

    <tbody>
        <c:forEach items="${systems}" var="system">
            <tr>
                <td><a href="./planets?systemId=${system.id}">${system.name}</a></td>
                <td><c:out value="${fn:toUpperCase(system.star)}"/></td>
                <td>${system.distance}</td>
            </tr>
        </c:forEach>
    </tbody>
</table>

<jsp:include page="footer.jsp"/>

stellar-web/src/main/webapp/jsf/addSystems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
>

<h:body>


        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="false"/>
            <ui:define name="title">
                #{msg['label.planetary.system.add.title']}
            </ui:define>
            <ui:define name="content">

                <h:form>
                    <h:outputLabel>#{msg['label.planetary.system.name']}</h:outputLabel>
                    <h:inputText required="true" value="#{planetarySystemForm.name}"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.star']}</h:outputLabel>
                    <h:inputText id="star" required="true"  maxlength="10" value="#{planetarySystemForm.star}">
                        <f:validateLength minimum="2" maximum="10"/>
                    </h:inputText>
                    <h:message for="star" style="color: red"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.distance']}</h:outputLabel>
                    <h:inputText id="distance" value="#{planetarySystemForm.distance}">
                        <f:validateDoubleRange minimum="0"/>
                    </h:inputText>
                    <h:message for="distance" style="color: red"/>
                    <br/>
                    <h:outputLabel >#{msg['label.planetary.system.discovery']}</h:outputLabel>
                    <h:inputText id="discovery" value="#{planetarySystemForm.discovery}">
                        <f:convertDateTime type="date" pattern="yyyy-MM-dd"/>
                    </h:inputText>
                    <h:message for="discovery" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.details']}</h:outputLabel>
                    <h:inputText id="details" value="#{planetarySystemForm.details}">
                        <f:converter converterId="urlConverter"/>
                    </h:inputText>
                    <h:message for="details" style="color: red;"/>
                    <br/>
                    <h:outputLabel>#{msg['label.planetary.system.next']}</h:outputLabel>
                    <h:selectBooleanCheckbox value="#{planetarySystemForm.next}"/>
                    <br/>
                    <h:commandButton
                            action="#{planetarySystemForm.add}"
                            value="${msg['label.planetary.system.add.button']}"/>
                </h:form>

            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-web/src/main/webapp/jsf/hello.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
>

<h:head>
    <title>JSF Hello World</title>
</h:head>
<h:body>
    <c:set var="customCriteria" value="#{helloBean.rendering}"/>

    <c:choose>
        <c:when test="#{not customCriteria}">
            <h:outputText value="Hello, #{helloBean.getName(param.name)}"/>
        </c:when>
        <c:otherwise>
            <h:outputText value="Hello, #{helloBean.getName('Jack')}"/>
        </c:otherwise>
    </c:choose>


</h:body>

</html>

stellar-web/src/main/webapp/jsf/planets.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"

>

<h:body>

        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="true"/>

            <ui:define name="title">

                <h:outputFormat value="#{msg['label.planets.list.title']}">
                    <f:param value="#{stellarBean.getPlanetarySystem(searchBean.systemId).name}"/>
                </h:outputFormat>

            </ui:define>

            <ui:define name="content">

                <h:dataTable
                        value="#{stellarBean.planets}"
                        var="p"
                >
                    <h:column headerText="Id">
                        <h:outputText value="#{p.id}"/>
                    </h:column>
                    <h:column headerText="Name">
                        <h:outputText value="#{p.name}"/>
                    </h:column>
                </h:dataTable>

            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-web/src/main/webapp/jsf/search.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
>
<f:view>
    <div id="search">
        <span>SEARCH</span>
        <h:form styleClass="search-container" >
            <h:inputText value="#{searchBean.phrase}"/>
            <h:commandButton/>
        </h:form>
    </div>
</f:view>
</html>

stellar-web/src/main/webapp/jsf/systems.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:jsf="http://xmlns.jcp.org/jsf"
>

<h:body>


        <ui:composition template="template.xhtml">
            <ui:param name="displaySearch" value="true"/>
            <ui:define name="title">
                Planetary Systems
            </ui:define>
            <ui:define name="content">
                <h:dataTable id="systemsTable" value="#{stellarBean.planetarySystems}" var="s">
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.name']}</f:facet>
                        <h:link value="#{s.name}" outcome="planets">
                            <f:param name="systemId" value="#{s.id}"/>
                        </h:link>

                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.star']}</f:facet>
                        <h:outputText value="#{s.star}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.distance']}</f:facet>
                        <h:outputText value="#{s.distance}"/>
                    </h:column>
                    <h:column>
                        <f:facet name="header">#{msg['label.planetary.system.discovery']}</f:facet>
                        <h:outputText value="#{s.discovery}">
                            <f:convertDateTime type="date" pattern="yyyy-MM-dd"/>
                        </h:outputText>
                    </h:column>
                </h:dataTable>
            </ui:define>

        </ui:composition>

</h:body>

</html>

stellar-web/src/main/webapp/jsf/template.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:f="http://java.sun.com/jsf/core"
>

<h:head>
    <title>Stellar</title>
    <h:outputStylesheet library="css" name="style-jsf.css"/>
    <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet"/>
</h:head>
<h:body>

    <header>
        <nav>
            <ul>
                <li class="active"><a
                        href="./systems.faces">Stellar Catalogue</a></li>
            </ul>
            <span>
                <h:form>
                    <h:selectOneMenu
                            value="#{localeBean.selectedLocale}"
                            onchange="submit()"
                    >
                        <f:selectItems
                                value="#{localeBean.supportedLocales}"
                                var="loc"
                                itemLabel="#{loc.getDisplayLanguage(loc)}"
                                itemValue="#{loc.language}"

                        />
                    </h:selectOneMenu>
                </h:form>
            </span>
        </nav>
    </header>

    <article>

        <c:if test="#{displaySearch}">
            <ui:include src="search.xhtml"/>
        </c:if>

        <section class="data">
            <span><ui:insert name="title">TODO</ui:insert></span>

            <ui:insert name="content"/>

        </section>
    </article>

    <footer>
        <span>JSF</span>
    </footer>



</h:body>

</html>